services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:${PGDATA}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"

  cache:
    container_name: redis_cache
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis.conf
    command: redis-server --requirepass ${REDIS_PASSWORD} /usr/local/etc/redis.conf

volumes:
  db:
